name: Build Plugin JAR File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test
      - name: Archive plugin-prismjs jar
        uses: actions/upload-artifact@v2
        with:
          name: plugin-prismjs
          path: |
            build/libs/*-plain.jar
          retention-days: 1
